// This file mirrors the structure generated by `flutterfire configure`.
// Replace each placeholder with the production values from your Firebase
// project before building a release (do not commit real secrets to source).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY_HERE',
    appId: 'YOUR_WEB_APP_ID_HERE',
    messagingSenderId: 'YOUR_WEB_MESSAGING_SENDER_ID',
    projectId: 'your-production-project-id',
    authDomain: 'your-production-project-id.firebaseapp.com',
    storageBucket: 'your-production-project-id.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE',
    appId: 'YOUR_ANDROID_APP_ID_HERE',
    messagingSenderId: 'YOUR_ANDROID_SENDER_ID',
    projectId: 'your-production-project-id',
    storageBucket: 'your-production-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE',
    appId: 'YOUR_IOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_IOS_SENDER_ID',
    projectId: 'your-production-project-id',
    storageBucket: 'your-production-project-id.appspot.com',
    iosBundleId: 'com.villageconnect.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY_HERE',
    appId: 'YOUR_MACOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_MACOS_SENDER_ID',
    projectId: 'your-production-project-id',
    storageBucket: 'your-production-project-id.appspot.com',
    iosBundleId: 'com.villageconnect.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY_HERE',
    appId: 'YOUR_WINDOWS_APP_ID_HERE',
    messagingSenderId: 'YOUR_WINDOWS_SENDER_ID',
    projectId: 'your-production-project-id',
    storageBucket: 'your-production-project-id.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY_HERE',
    appId: 'YOUR_LINUX_APP_ID_HERE',
    messagingSenderId: 'YOUR_LINUX_SENDER_ID',
    projectId: 'your-production-project-id',
    storageBucket: 'your-production-project-id.appspot.com',
  );
}
